name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: install yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install yarn -g

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          yarn add electron

      - name: install dependencies for fixtures
        run: |
          cd fixtures/demo
          yarn install
          cd ../../

      - name: gabrielbb/xvfb-action
        uses: GabrielBB/xvfb-action@v1.4
        with:
          working-directory: ./
          run: yarn test
